### ISSUE TITLE
Cannot Install comfyUI and llama.cpp

### ISSUE THREAD

**Issue by jackphj** [intel/AI-Playground#133]
## Problem
I tried several times but i connot install ComfyUI and llama.cpp. How can i solve the issue
![image](https://github.com/user-attachments/assets/fe959444-092c-42c1-b5ee-3d195a2b5984)

![image](https://github.com/user-attachments/assets/bf5826e7-3dbd-4e25-9f0b-1dd71b9900ee)

## Environment (please complete the following information):

- OS: [e.g. Windows11 24H2]
- CPU: [e.g. Ultra7 258v]
- Version: [2.0-prev]

**Comment by jackphj** [comment]
i delete all dir included "comfyUI" and "llama", then i try installing them. here is the log
![image](https://github.com/user-attachments/assets/592ba750-5414-42ee-913c-d726187495f3)
![image](https://github.com/user-attachments/assets/7d18f0c3-2da4-4861-8ba8-882616093d78)

**Comment by qiacheng** [comment]
can you backup  your models and fully uninstall AI playground then reinstall?

when installing llama.cpp-gguf components, check the install location and see if there is requirements.txt in AIPG install location/resources/LlamaCPP

Also check the storage space of your C drive as well

**Comment by jackphj** [comment]
> can you backup your models and fully uninstall AI playground then reinstall?你可以备份你的模型并完全卸载AI游乐场然后重新安装吗？
> 
> when installing llama.cpp-gguf components, check the install location and see if there is requirements.txt in AIPG install location/resources/LlamaCPP安装llama.cpp-gguf组件时，检查安装位置，看看AIPG安装位置/resources/LlamaCPP中是否有requirements.txt
> 
> Also check the storage space of your C drive as well

i reinstall ai playground 5 times and i found that if i select install for all user, i cannot install all components. 

if i select just for me, i can install ai playground and somtimes i can install llama.cpp. however, i  never successfully install comfyUI, in the last time, log as below:

>![image](https://github.com/user-attachments/assets/f04687be-df48-4c10-99f2-e13a8ac743bb)

>![image](https://github.com/user-attachments/assets/9e29210a-4baa-41b3-9bff-762a44616aea)

**Comment by MadamePingShockwave** [comment]
Are you in mainland China? Looks like a network issue. I came across a similar problem, and solved it by using a proxy and enabling the TUN mode. Initially I didn't use VPN and the AI Playground component was installed smoothly but the setup failed to install ComfyUI. (I also tried to delete the temp folder and reinstall for many times but all failed.) As far as I can recall, the dev log said the problem was that the setup program tried to use git to download something but timed out due to github being blocked. As the global proxy doesn't work for git and I didn't want to configure manually for all the possible tools the setup program internally used, I enabled the TUN mode, deleted all the temp folders and then reinstalled. Problem solved! Not totally the same as your case, but your log seems to show that pip failed to install some necessary packages, possibly due to network issues, too.

**Comment by jackphj** [comment]
> Are you in mainland China? Looks like a network issue. I came across a similar problem, and solved it by using a proxy and enabling the TUN mode. Initially I didn't use VPN and the AI Playground component was installed smoothly but the setup failed to install ComfyUI. (I also tried to delete the temp folder and reinstall for many times but all failed.) As far as I can recall, the dev log said the problem was that the setup program tried to use git to download something but timed out due to github being blocked. As the global proxy doesn't work for git and I didn't want to configure manually for all the possible tools the setup program internally used, I enabled the TUN mode, deleted all the temp folders and then reinstalled. Problem solved! Not totally the same as your case, but your log seems to show that pip failed to install some necessary packages, possibly due to network issues, too.

thanks, it's useful
