### ISSUE TITLE
Unable to install AI Playground or its components

### ISSUE THREAD

**Issue by PyryAnttila** [intel/AI-Playground#135]
## Describe the bug

Failure to install "Intel AI Playground" and other related components using the 2.0a installer. Repairing does not work.

## To Reproduce

1. Launch the latest version v2.0.0-alpha-prev.exe
2. Go through the installation process until you arrive @ AI Playground Setup
3. Attempt to install components
4. All component installations fail after a few seconds

## Expected behavior

I expected the components to install themselves.

## Screenshots

![AI_Playground_dQexsujZyY](https://github.com/user-attachments/assets/941bc928-6f64-47de-8f8e-b2f03de72597)

## Environment (please complete the following information):

- OS: Windows 11 Pro
- GPU: Intel Arc B580 12GB
- CPU: Intel Core i9-14900KS
- Version: v2.0.0-alpha-prev

## Additional context

Followed common troubleshooting steps, no help.

Restarted my PC. Launched the software in administrator mode. Attempted to switch accounts on Windows and turn off all non-Microsoft services, turned off firewall completely in case the connection is being blocked by the firewall, tried using WiFi and Mobile Hotspot to no avail. Launched PC in troubleshooting mode with Ethernet connection, no help. Reinstalled AI Playground multiple times.

The device is visible in Device Manager and hashcat also picks it up and works as it should.

I am using the latest drivers: 32.0.101.6253

00:07:18|llamacpp-backend|Installed 18 packages in 132ms
 + dpcpp-cpp-rt==2024.2.1
 + intel-cmplr-lib-rt==2024.2.1
 + intel-cmplr-lib-ur==2024.2.1
 + intel-cmplr-lic-rt==2024.2.1
 + intel-opencl-rt==2024.2.1
 + intel-openmp==2024.2.1
 + intel-sycl-rt==2024.2.1
 + mkl==2024.2.1
 + mkl-dpcpp==2024.2.1
 + onemkl-sycl-blas==
00:07:18|llamacpp-backend|2024.2.1
 + onemkl-sycl-datafitting==2024.2.1
 + onemkl-sycl-dft==2024.2.1
 + onemkl-sycl-lapack==2024.2.1
 + onemkl-sycl-rng==2024.2.1
 + onemkl-sycl-sparse==2024.2.1
 + onemkl-sycl-stats==2024.2.1
 + onemkl-sycl-vm==2024.2.1
 + tbb==2021.13.1

00:07:18|llamacpp-backend|Spawning command C:\Program Files\AI Playground\resources\llamacpp-backend-env_tmp\Library\bin\ls_level_zero.exe 
00:07:18|llamacpp-backend|Extra env: {"ONEAPI_DEVICE_SELECTOR":"level_zero:*"}
00:07:20|llamacpp-backend|Failure to identify intel hardware. Error: Error: command C:\Program Files\AI Playground\resources\llamacpp-backend-env_tmp\Library\bin\ls_level_zero.exe  failed 3221226505
00:07:20|llamacpp-backend|Set up of service failed due to Error: Failure to identify intel hardware. Error: Error: command C:\Program Files\AI Playground\resources\llamacpp-backend-env_tmp\Library\bin\ls_level_zero.exe  failed 3221226505
00:07:20|llamacpp-backend|Aborting set up of llamacpp-backend service environment
00:07:29|ai-backend|Cloning archetype python env C:\Program Files\AI Playground\resources\prototype-python-env into C:\Program Files\AI Playground\resources\ai-backend-env_tmp
00:07:29|ai-backend|Cleaning up previously containment directory at C:\Program Files\AI Playground\resources\ai-backend-env_tmp
00:07:30|ai-backend|Spawning command C:\Program Files\AI Playground\resources\ai-backend-env_tmp\python.exe -m uv pip install -r C:\Program Files\AI Playground\resources\service\requirements-ls_level_zero.txt
00:07:31|ai-backend|Using Python 3.11.10 environment at: resources\ai-backend-env_tmp

00:07:31|ai-backend|Resolved 18 packages in 3ms

00:07:31|ai-backend|Installed 18 packages in 157ms
 
00:07:31|ai-backend|+ dpcpp-cpp-rt==2024.2.1
 + intel-cmplr-lib-rt==2024.2.1
 + intel-cmplr-lib-ur==2024.2.1
 + intel-cmplr-lic-rt==2024.2.1
 + intel-opencl-rt==2024.2.1
 + intel-openmp==2024.2.1
 + intel-sycl-rt==2024.2.1
 + mkl==2024.2.1
 + mkl-dpcpp==2024.2.1
 
00:07:31|ai-backend|+ onemkl-sycl-blas==2024.2.1
 + onemkl-sycl-datafitting==2024.2.1
 + onemkl-sycl-dft==2024.2.1
 + onemkl-sycl-lapack==2024.2.1
 + onemkl-sycl-rng==2024.2.1
 + onemkl-sycl-sparse
00:07:31|ai-backend|==2024.2.1
 + onemkl-sycl-stats==2024.2.1
 + onemkl-sycl-vm==2024.2.1
 + tbb==2021.13.1

00:07:31|ai-backend|Spawning command C:\Program Files\AI Playground\resources\ai-backend-env_tmp\Library\bin\ls_level_zero.exe 
00:07:31|ai-backend|Extra env: {"ONEAPI_DEVICE_SELECTOR":"level_zero:*"}
00:07:33|ai-backend|Failure to identify intel hardware. Error: Error: command C:\Program Files\AI Playground\resources\ai-backend-env_tmp\Library\bin\ls_level_zero.exe  failed 3221226505
00:07:33|ai-backend|Set up of service failed due to Error: Failure to identify intel hardware. Error: Error: command C:\Program Files\AI Playground\resources\ai-backend-env_tmp\Library\bin\ls_level_zero.exe  failed 3221226505
00:07:33|ai-backend|Aborting set up of ai-backend service environment

**Comment by Nuullll** [comment]
Could you try to remove these folders and then launch AI Playground again?
- `C:\Program Files\AI Playground\resources\ai-backend-env_tmp`
- `C:\Program Files\AI Playground\resources\ai-backend-env`
- `C:\Program Files\AI Playground\resources\comfyui-backend-env_tmp`
- `C:\Program Files\AI Playground\resources\comfyui-backend-env`
- `C:\Program Files\AI Playground\resources\llama-cpp-env_tmp`
- `C:\Program Files\AI Playground\resources\llama-cpp-env`

The repair/install functionality in version 2.0.0-alpha-preview had some bugs, but we have addressed multiple issues to improve the user experience. We expect the next release to be much better.

Thank you for your patience.

**Comment by PyryAnttila** [comment]
> Could you try to remove these folders and then launch AI Playground again?
> 
>     * `C:\Program Files\AI Playground\resources\ai-backend-env_tmp`
> 
>     * `C:\Program Files\AI Playground\resources\ai-backend-env`
> 
>     * `C:\Program Files\AI Playground\resources\comfyui-backend-env_tmp`
> 
>     * `C:\Program Files\AI Playground\resources\comfyui-backend-env`
> 
>     * `C:\Program Files\AI Playground\resources\llama-cpp-env_tmp`
> 
>     * `C:\Program Files\AI Playground\resources\llama-cpp-env`
> 
> 
> The repair/install functionality in version 2.0.0-alpha-preview had some bugs, but we have addressed multiple issues to improve the user experience. We expect the next release to be much better.
> 
> Thank you for your patience.

Hi! Thank you for your response.

Only the tmp folders exist for me. I tried deleting those and relaunching AI Playground. No luck.

**Comment by PyryAnttila** [comment]
Reinstalling the drivers worked. No idea what caused the error though, as I had just reinstalled them too the day prior with a clean installation.

**Comment by pixeldigitale** [comment]
Hi, here I have the same issue as reported, I can't install AI Playground and ComfyUI component.
Intel ARC B580 on Windows 11
Current driver: 32.0.101.6256
AI Playground version: v2.0.0-alpha-prev

![immagine](https://github.com/user-attachments/assets/1230694e-9ee5-42bc-91bb-5ce74c043e09)

Tried to reinstall the graphics driver as suggested, it didn't work. Also tried to delete the tmp folders and relaunch the AI Playground (admin and non-admin) without success.

Here you can find the log:

07:25:37|ai-backend|Cloning archetype python env E:\AI Playground\resources\prototype-python-env into E:\AI Playground\resources\ai-backend-env_tmp
07:25:38|ai-backend|Spawning command E:\AI Playground\resources\ai-backend-env_tmp\python.exe -m uv pip install -r E:\AI Playground\resources\service\requirements-ls_level_zero.txt
07:25:39|ai-backend|Using Python 3.11.10 environment at: resources\ai-backend-env_tmp

07:25:39|ai-backend|Resolved 18 packages in 2ms

07:25:39|ai-backend|warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.

07:25:39|ai-backend|Installed 18 packages in 254ms
 +
07:25:39|ai-backend| dpcpp-cpp-rt==2024.2.1
 + intel-cmplr-lib-rt==2024.2.1
 + intel-cmplr-lib-ur==2024.2.1
 + intel-cmplr-lic-rt==2024.2.1
 + intel-opencl-rt==2024.2.1
 +
07:25:39|ai-backend| intel-openmp==2024.2.1
 + intel-sycl-rt==2024.2.1
 + mkl==2024.2.1
 + mkl-dpcpp==2024.2.1
07:25:39|ai-backend|
 + onemkl-sycl-blas==2024.2.1
 + onemkl-sycl-datafitting==2024.2.1
 + onemkl-sycl-dft==2024.2.1
07:25:39|ai-backend|
 + onemkl-sycl-lapack==2024.2.1
 + onemkl-sycl-rng==2024.2.1
 + onemkl-sycl-sparse==2024.2.1
07:25:39|ai-backend|
 + onemkl-sycl-stats==
07:25:39|ai-backend|2024.2.1
 + onemkl-sycl-vm==2024.2.1
 + tbb==2021.13.1
07:25:39|ai-backend|

07:25:39|ai-backend|Spawning command E:\AI Playground\resources\ai-backend-env_tmp\Library\bin\ls_level_zero.exe 
07:25:39|ai-backend|Extra env: {"ONEAPI_DEVICE_SELECTOR":"level_zero:*"}
07:25:40|ai-backend|ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 

07:25:40|ai-backend|ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll

07:25:40|ai-backend|[{"id": 0, "name": "Intel(R) Arc(TM) B580 Graphics", "device_id": 57867}]

07:25:40|ai-backend|Installing dependency E:\AI Playground\resources\intel_extension_for_pytorch-2.3.110+xpu-cp311-cp311-win_amd64.whl for E:\AI Playground\resources\ai-backend-env_tmp
07:25:40|ai-backend|Spawning command E:\AI Playground\resources\ai-backend-env_tmp\python.exe -m pip install E:\AI Playground\resources\intel_extension_for_pytorch-2.3.110+xpu-cp311-cp311-win_amd64.whl
07:25:41|ai-backend|Processing e:\ai playground\resources\intel_extension_for_pytorch-2.3.110+xpu-cp311-cp311-win_amd64.whl

07:25:42|ai-backend|Collecting psutil (from intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached psutil-6.1.1-cp37-abi3-win_amd64.whl.metadata (23 kB)

07:25:42|ai-backend|Collecting numpy (from intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached numpy-2.2.1-cp311-cp311-win_amd64.whl.metadata (60 kB)

07:25:42|ai-backend|Collecting packaging (from intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)

07:25:42|ai-backend|Collecting pydantic (from intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached pydantic-2.10.4-py3-none-any.whl.metadata (29 kB)

07:25:42|ai-backend|Collecting ruamel.yaml (from intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)

07:25:42|ai-backend|Requirement already satisfied: dpcpp-cpp-rt==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: mkl-dpcpp==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: intel-openmp==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: intel-opencl-rt==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)
Requirement already satisfied: intel-sycl-rt==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: mkl==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-blas==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-lapack==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-dft==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-sparse==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-vm==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-rng==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-stats==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: onemkl-sycl-datafitting==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from mkl-dpcpp==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: tbb==2021.* in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-opencl-rt==2024.2.1->dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2021.13.1)

07:25:42|ai-backend|Requirement already satisfied: intel-cmplr-lic-rt==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-opencl-rt==2024.2.1->dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: intel-cmplr-lib-ur==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-openmp==2024.2.1->dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Requirement already satisfied: intel-cmplr-lib-rt==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from intel-sycl-rt==2024.2.1->dpcpp-cpp-rt==2024.2.1->intel-extension-for-pytorch==2.3.110+xpu) (2024.2.1)

07:25:42|ai-backend|Collecting annotated-types>=0.6.0 (from pydantic->intel-extension-for-pytorch==2.3.110+xpu)

07:25:42|ai-backend|  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)

07:25:43|ai-backend|Collecting pydantic-core==2.27.2 (from pydantic->intel-extension-for-pytorch==2.3.110+xpu)

07:25:43|ai-backend|  Using cached pydantic_core-2.27.2-cp311-cp311-win_amd64.whl.metadata (6.7 kB)

07:25:43|ai-backend|Collecting typing-extensions>=4.12.2 (from pydantic->intel-extension-for-pytorch==2.3.110+xpu)

07:25:43|ai-backend|  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)

07:25:43|ai-backend|Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml->intel-extension-for-pytorch==2.3.110+xpu)

07:25:43|ai-backend|  Using cached ruamel.yaml.clib-0.2.12-cp311-cp311-win_amd64.whl.metadata (2.8 kB)

07:25:43|ai-backend|Using cached numpy-2.2.1-cp311-cp311-win_amd64.whl (12.9 MB)

07:25:43|ai-backend|Using cached packaging-24.2-py3-none-any.whl (65 kB)

07:25:43|ai-backend|Using cached psutil-6.1.1-cp37-abi3-win_amd64.whl (254 kB)

07:25:43|ai-backend|Using cached pydantic-2.10.4-py3-none-any.whl (431 kB)

07:25:43|ai-backend|Using cached pydantic_core-2.27.2-cp311-cp311-win_amd64.whl (2.0 MB)

07:25:43|ai-backend|Using cached ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)

07:25:43|ai-backend|Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)

07:25:43|ai-backend|Using cached ruamel.yaml.clib-0.2.12-cp311-cp311-win_amd64.whl (118 kB)

07:25:43|ai-backend|Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)

07:25:43|ai-backend|Installing collected packages: typing-extensions, ruamel.yaml.clib, psutil, packaging, numpy, annotated-types, ruamel.yaml, pydantic-core, pydantic, intel-extension-for-pytorch

07:25:48|ai-backend|  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'E:\AI Playground\resources\ai-backend-env_tmp\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

07:25:56|ai-backend|  WARNING: The script ipexrun.exe is installed in 'E:\AI Playground\resources\ai-backend-env_tmp\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

07:25:57|ai-backend|Successfully installed annotated-types-0.7.0 intel-extension-for-pytorch-2.3.110+xpu numpy-2.2.1 packaging-24.2 psutil-6.1.1 pydantic-2.10.4 pydantic-core-2.27.2 ruamel.yaml-0.18.10 ruamel.yaml.clib-0.2.12 typing-extensions-4.12.2

07:25:57|ai-backend|Successfully installed of dependency E:\AI Playground\resources\intel_extension_for_pytorch-2.3.110+xpu-cp311-cp311-win_amd64.whl for E:\AI Playground\resources\ai-backend-env_tmp
07:25:57|ai-backend|Installing python dependencies for E:\AI Playground\resources\ai-backend-env_tmp
07:25:57|ai-backend|Spawning command E:\AI Playground\resources\ai-backend-env_tmp\python.exe -m pip install -r E:\AI Playground\resources\service\requirements-bmg.txt
07:25:58|ai-backend|Looking in indexes: https://pypi.org/simple, https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/, https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

07:25:58|ai-backend|Requirement already satisfied: mkl-dpcpp==2024.2.1 in e:\ai playground\resources\ai-backend-env_tmp\lib\site-packages (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 4)) (2024.2.1)

07:25:59|ai-backend|Collecting torch==2.3.1.post0+cxx11.abi (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 5))

07:25:59|ai-backend|  ERROR: HTTP error 403 while getting https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from https://pytorch-extension.intel.com/release-whl/stable/xpu/us/torch/)

07:26:00|ai-backend|ERROR: Could not install requirement torch==2.3.1.post0+cxx11.abi from https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 5)) because of HTTP error 403 Client Error: Forbidden for url: https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl for URL https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from https://pytorch-extension.intel.com/release-whl/stable/xpu/us/torch/)

07:26:00|ai-backend|Failure during installation of python dependencies for E:\AI Playground\resources\ai-backend-env_tmp. Error: Error: command E:\AI Playground\resources\ai-backend-env_tmp\python.exe -m,pip,install,-r,E:\AI Playground\resources\service\requirements-bmg.txt failed 1
07:26:00|ai-backend|Set up of service failed due to Error: Failed to install python dependencies for E:\AI Playground\resources\ai-backend-env_tmp. Error: Error: command E:\AI Playground\resources\ai-backend-env_tmp\python.exe -m,pip,install,-r,E:\AI Playground\resources\service\requirements-bmg.txt failed 1
07:26:00|ai-backend|Aborting set up of ai-backend service environment
07:26:01|comfyui-backend|Cloning archetype python env E:\AI Playground\resources\prototype-python-env into E:\AI Playground\resources\comfyui-backend-env_tmp
07:26:02|comfyui-backend|Spawning command E:\AI Playground\resources\comfyui-backend-env_tmp\python.exe -m uv pip install -r E:\AI Playground\resources\service\requirements-ls_level_zero.txt
07:26:03|comfyui-backend|Using Python 3.11.10 environment at: resources\comfyui-backend-env_tmp

07:26:03|comfyui-backend|Resolved 18 packages in 33ms

07:26:03|comfyui-backend|warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.

07:26:05|comfyui-backend|Installed 18 packages in 1.94s
 + dpcpp-cpp-rt==
07:26:05|comfyui-backend|2024.2.1
 + intel-cmplr-lib-rt==2024.2.1
 + intel-cmplr-lib-ur==2024.2.1
 + intel-cmplr-lic-rt==2024.2.1
 + intel-opencl-rt==2024.2.1
 + intel-openmp==2024.2.1
 +
07:26:05|comfyui-backend| intel-sycl-rt==2024.2.1
 + mkl==2024.2.1
 + mkl-dpcpp==2024.2.1
07:26:05|comfyui-backend|
 + onemkl-sycl-blas==2024.2.1
 + onemkl-sycl-datafitting==2024.2.1
 +
07:26:05|comfyui-backend| onemkl-sycl-dft==2024.2.1
 + onemkl-sycl-lapack==2024.2.1
 + onemkl-sycl-rng==
07:26:05|comfyui-backend|2024.2.1
 + onemkl-sycl-sparse==2024.2.1
 + onemkl-sycl-stats==2024.2.1
 + 
07:26:05|comfyui-backend|onemkl-sycl-vm==2024.2.1
 + tbb==2021.13.1

07:26:05|comfyui-backend|Spawning command E:\AI Playground\resources\comfyui-backend-env_tmp\Library\bin\ls_level_zero.exe 
07:26:05|comfyui-backend|Extra env: {"ONEAPI_DEVICE_SELECTOR":"level_zero:*"}
07:26:06|comfyui-backend|ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 

07:26:06|comfyui-backend|ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll

07:26:06|comfyui-backend|[{"id": 0, "name": "Intel(R) Arc(TM) B580 Graphics", "device_id": 57867}]

07:26:06|comfyui-backend|Installing python dependencies for E:\AI Playground\resources\comfyui-backend-env_tmp
07:26:06|comfyui-backend|Spawning command E:\AI Playground\resources\comfyui-backend-env_tmp\python.exe -m pip install -r E:\AI Playground\resources\service\requirements-bmg.txt
07:26:07|comfyui-backend|Looking in indexes: https://pypi.org/simple, https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/, https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

07:26:07|comfyui-backend|Requirement already satisfied: mkl-dpcpp==2024.2.1 in e:\ai playground\resources\comfyui-backend-env_tmp\lib\site-packages (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 4)) (2024.2.1)

07:26:08|comfyui-backend|Collecting torch==2.3.1.post0+cxx11.abi (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 5))

07:26:08|comfyui-backend|  ERROR: HTTP error 403 while getting https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from https://pytorch-extension.intel.com/release-whl/stable/xpu/us/torch/)

07:26:08|comfyui-backend|ERROR: Could not install requirement torch==2.3.1.post0+cxx11.abi from https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from -r E:\AI Playground\resources\service\requirements-bmg.txt (line 5)) because of HTTP error 403 Client Error: Forbidden for url: https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl for URL https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/./torch-2.3.1.post0%2Bcxx11.abi-cp311-cp311-win_amd64.whl (from https://pytorch-extension.intel.com/release-whl/stable/xpu/us/torch/)

07:26:09|comfyui-backend|Failure during installation of python dependencies for E:\AI Playground\resources\comfyui-backend-env_tmp. Error: Error: command E:\AI Playground\resources\comfyui-backend-env_tmp\python.exe -m,pip,install,-r,E:\AI Playground\resources\service\requirements-bmg.txt failed 1
07:26:09|comfyui-backend|Set up of service failed due to Error: Failed to install python dependencies for E:\AI Playground\resources\comfyui-backend-env_tmp. Error: Error: command E:\AI Playground\resources\comfyui-backend-env_tmp\python.exe -m,pip,install,-r,E:\AI Playground\resources\service\requirements-bmg.txt failed 1
07:26:09|comfyui-backend|Aborting set up of comfyui-backend service environment
