### ISSUE TITLE
Hangs on loading screen.

### ISSUE THREAD

**Issue by Nachash613** [intel/AI-Playground#57]
## Describe the bug

On fresh install of windows 11 pro system using arc a770 16GB gpu, all drivers good and newly installed, hangs on loading screen. No indication as to why this is happening, but during installation process a lot of python packages are showing up as detected and uninstalled. Not sure if installer is breaking python libraries.

**Comment by PrankKillTV** [comment]
Same issue here. Just downloaded it today for first time and it just plays pong for hours!

**Comment by theawless** [comment]
This thread helped me fix the issue: https://github.com/intel/AI-Playground/issues/26

**Comment by jimbolimbo3** [comment]
Just reinstall Microsoft Visual C++ Redistributable, [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by Nuullll** [comment]
For unknown reason, issue #26 was gone :-(

You can see the actual error with following steps:
1. Open a cmd under `<InstallationDirectory>\resources\service`
2. Execute `..\env\python.exe .\web_api.py` and post the log here

**Comment by Nuullll** [comment]
@glee920 could you please take a screenshot to show where you are stuck?

**Comment by xuanthuc1502** [comment]
> For unknown reason, issue #26 was gone :-(
> 
> You can see the actual error with following steps:
> 
> 1. Open a cmd under `<InstallationDirectory>\resources\service`
> 2. Execute `..\env\python.exe .\web_api.py` and post the log here

my log "OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\ASUS\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies."

**Comment by Nuullll** [comment]
> > For unknown reason, issue #26 was gone :-(
> > You can see the actual error with following steps:
> > 
> > 1. Open a cmd under `<InstallationDirectory>\resources\service`
> > 2. Execute `..\env\python.exe .\web_api.py` and post the log here
> 
> my log "OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\ASUS\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies."

install Microsoft Visual C++ Redistributable, https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by glee920** [comment]
I still got the same error after installing Microsoft Visual C++ Redistributable.

C:\Windows\System32>cd C:\Program Files\AI Playground\resources\service

C:\Program Files\AI Playground\resources\service>..\env\python.exe .\web_api.py
Traceback (most recent call last):
  File "C:\Program Files\AI Playground\resources\service\web_api.py", line 5, in <module>
    from llm_adapter import LLM_SSE_Adapter
  File "C:\Program Files\AI Playground\resources\service\llm_adapter.py", line 5, in <module>
    import llm_biz
  File "C:\Program Files\AI Playground\resources\service\llm_biz.py", line 6, in <module>
    import torch
  File "C:\Program Files\AI Playground\resources\env\Lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Program Files\AI Playground\resources\env\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

**Comment by Jamesrggg** [comment]
Hello! I have a similar issue stuck loading with a different log error. I have installed Microsoft Visual C++ Redistributable and  updated everything I can think of.

PS C:\Users\james\AppData\Local\Programs\AI Playground\resources\service> ..\env\python.exe .\web_api.py
C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path:
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll

**Comment by Nuullll** [comment]
Fixed by [v1.22](https://github.com/intel/AI-Playground/releases/tag/v1.22beta)
